# NOTE: FOUR ENVVARS TO SET IN CIRCLECI
# GOOGLE_ANALYTICS_ID
# NOW_TOKEN
# SITE_DOMAIN_DEV
# SITE_DOMAIN_PROD
version: 2
jobs:
  checkout_code:
    docker:
      - image: 'circleci/node:latest'
    working_directory: ~/mashaeltsova-photography
    steps:
      - checkout
      - attach_workspace:
          at: ~/mashaeltsova-photography
      - restore_cache:
          keys:
            - 'yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}'
            - 'yarn-cache-{{ .Branch }}'
            - yarn-cache-
      - run: yarn install
      - save_cache:
          key: 'yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}'
          paths: node_modules
      - persist_to_workspace:
          root: .
          paths: .
  test_and_report:
    docker:
      - image: 'circleci/node:latest'
    working_directory: ~/mashaeltsova-photography
    steps:
      - attach_workspace:
          at: ~/mashaeltsova-photography
      - run: yarn start test.coverage
      - run: yarn start reportCoverage
      - store_artifacts:
          path: ./coverage/clover.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: ./coverage/clover.xml
  build:
    docker:
      - image: 'circleci/node:latest'
    working_directory: ~/mashaeltsova-photography
    steps:
      - attach_workspace:
          at: ~/mashaeltsova-photography
      - run:
          name: yarn build
          command: |
            if [ "${CIRCLE_BRANCH}" == "version-2" ]; then
              GOOGLE_ANALYTICS_ID=${GOOGLE_ANALYTICS_ID} SITE_DOMAIN=${SITE_DOMAIN_DEV} yarn ci_build
            elif [ "${CIRCLE_BRANCH}" == "production" ]; then
              GOOGLE_ANALYTICS_ID=${GOOGLE_ANALYTICS_ID} SITE_DOMAIN=${SITE_DOMAIN_PROD} yarn ci_build
            else
              echo "This failed miserably!"
            fi
      - persist_to_workspace:
          root: .
          paths: .
  deployment:
    docker:
      - image: 'circleci/node:latest'
    working_directory: ~/mashaeltsova-photography
    steps:
      - attach_workspace:
          at: ~/mashaeltsova-photography
      - run: sudo yarn global add now
      - deploy:
          name: Deploy & Alias.
          command: |
            if [ "${CIRCLE_BRANCH}" == "version-2" ]; then
              url=$(now public --token=${NOW_TOKEN} -n="mashas-site" --static 2>/dev/null)
              echo "Site deployed to ${url}."
              now --token=${NOW_TOKEN} alias $url mashas-site-v2
            elif [ "${CIRCLE_BRANCH}" == "production" ]; then
              url=$(now public --token=${NOW_TOKEN} -n="mashas-site" --static 2>/dev/null)
              echo "Site deployed to ${url}."
              now --token=${NOW_TOKEN} alias $url mashaeltsovaphotography.com
            else
              echo "This failed miserably!"
            fi
workflows:
  version: 2
  test_build_deploy:
    jobs:
      - checkout_code
      - test_and_report:
          requires:
            - checkout_code
      - build:
          requires:
            - test_and_report
      - deployment:
          requires:
            - test_and_report
            - build
          filters:
            branches:
              only:
                - production
                - version-2
