version: 2
jobs:
  checkout_code:
    docker:
      - image: circleci/node:latest
    working_directory: ~/mashaeltsova-photography
    steps:
      - checkout
      - attach_workspace:
          at: ~/mashaeltsova-photography
      - restore_cache:
          keys:
            - yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-cache-{{ .Branch }}
            - yarn-cache-
      - run: yarn install
      - save_cache:
          key: yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths: node_modules
      - persist_to_workspace:
          root: .
          paths: .
  test_and_report:
    docker:
      - image: circleci/node:latest
    working_directory: ~/mashaeltsova-photography
    steps:
      - attach_workspace:
          at: ~/mashaeltsova-photography
      - run: yarn install
      - run: yarn start validate.withCoverage
      - run: yarn start reportCoverage
      - store_artifacts:
          path: ./coverage/clover.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: ./coverage/clover.xml
  deployment:
    docker:
      - image: circleci/node:latest
    working_directory: ~/mashaeltsova-photography
    steps:
      - attach_workspace:
          at: ~/mashaeltsova-photography
      - run: yarn install
      - run: sudo yarn global add now
      - deploy:
          name: Deploy & Alias.
          command: |
            if [ "${CIRCLE_BRANCH}" == "production" ]; then
              now -t ${NOW_TOKEN} -n=mashaeltsova-photography
              now -t ${NOW_TOKEN} alias mashaeltsovaphotography.com
            elif [ "${CIRCLE_BRANCH}" == "master" ]; then
              now -t ${NOW_TOKEN} -n=mashaeltsova-photography
              now -t ${NOW_TOKEN} alias mashaeltsova-photography-beta.now.sh
            else
              echo "Should not get here ever."
            fi
workflows:
  version: 2
  test_and_deploy:
    jobs:
      - checkout_code
      - test_and_report:
          requires:
            - checkout_code
      - deployment:
          requires:
            - test_and_report
          filters:
            branches:
              only:
                - master
                - production
